// draft_data.js
// Separate mode: Team Draft Royale (does not share files with Prompt Debate mode).

window.DRAFT_TEAM_DATA = {
  defaultRounds: 5,

  roles: [
    { id: 'captain', name: 'Captain', blurb: 'Last fighter; sets the strategic plan.' },
    { id: 'vice', name: 'Vice Captain', blurb: 'All-rounder; can handle any role under pressure.' },
    { id: 'tank', name: 'Tank', blurb: 'Draws aggro first 60 seconds; must endure focus.' },
    { id: 'assassin', name: 'Assassin', blurb: 'Fights alone; thrives isolated.' },
    { id: 'support', name: 'Support', blurb: 'Helps first (shield/heal/revive); fights second.' },
  ],

  modifiers: [
    'No flying (any flight/levitation is disabled).',
    'Powers/Magic sealed for the first 30 seconds.',
    'The battle becomes a chess match between Captains (no direct combat).',
    'Urban battlefield with civilians: collateral damage loses you the vote.',
    'No killing allowed: incapacitation only.',
    'Everyone fights 1v1 (Assassins shine; teams must regroup).',
    'Captain and Support swap characters.',
    'Captain and Support team up, Vice Captain and Tank team up, Assassin remain alone.',
    'Support is targeted first (protect them or lose).',
    'Everyone has to agree on removing/nullifying 1 role this round.',
  ],

  // Character pool objects: { name, anime }
  characters: [
        
        // Dragon Ball
        { name: "Kid Goku", anime: "Dragon Ball" },
        { name: "Bulma", anime: "Dragon Ball" },
        { name: "Master Roshi", anime: "Dragon Ball" },
        { name: "Krillin", anime: "Dragon Ball" },
        { name: "Piccolo", anime: "Dragon Ball" },
        { name: "Yamcha", anime: "Dragon Ball" },
        { name: "Tien Shinhan", anime: "Dragon Ball" },
        { name: "Chi-Chi", anime: "Dragon Ball" },
        { name: "Launch", anime: "Dragon Ball" },
        { name: "Emperor Pilaf", anime: "Dragon Ball" },

        // Dragon Ball Z
        { name: "Teen Gohan", anime: "Dragon Ball Z" },
        { name: "Future Trunks", anime: "Dragon Ball Z" },
        { name: "Frieza", anime: "Dragon Ball Z" },
        { name: "Cell", anime: "Dragon Ball Z" },
        { name: "Kid Buu", anime: "Dragon Ball Z" },
        { name: "Hercules", anime: "Dragon Ball Z" },
        { name: "Android 16", anime: "Dragon Ball Z" },
        { name: "Android 18", anime: "Dragon Ball Z" },
        { name: "Majin Vegeta", anime: "Dragon Ball Z" },
        { name: "Gotenks", anime: "Dragon Ball Z" },

        // Dragon Ball GT
        { name: "Super Saiyan 4 Gogeta", anime: "Dragon Ball GT" },
        { name: "Omega Shenron", anime: "Dragon Ball GT" },
        { name: "Super 17", anime: "Dragon Ball GT" },
        { name: "Pan", anime: "Dragon Ball GT" },
        { name: "Baby Vegeta", anime: "Dragon Ball GT" },
        { name: "Super Saiyan 4 Goku", anime: "Dragon Ball GT" },
        { name: "Super Saiyan 4 Vegeta", anime: "Dragon Ball GT" },
        { name: "Uub (GT)", anime: "Dragon Ball GT" },
        { name: "Nuova Shenron", anime: "Dragon Ball GT" },
        { name: "Giru", anime: "Dragon Ball GT" },

        // Dragon Ball Super
        { name: "Super Saiyan Blue Vegito", anime: "Dragon Ball Super" },
        { name: "Super Saiyan Blue Gogeta", anime: "Dragon Ball Super" },
        { name: "Goku", anime: "Dragon Ball Super" },
        { name: "Vegeta", anime: "Dragon Ball Super" },
        { name: "Beerus", anime: "Dragon Ball Super" },
        { name: "Jiren", anime: "Dragon Ball Super" },
        { name: "Broly (DBS)", anime: "Dragon Ball Super" },
        { name: "Goku Black", anime: "Dragon Ball Super" },
        { name: "Ultra Instinct Goku", anime: "Dragon Ball Super" },
        { name: "Hit", anime: "Dragon Ball Super" },
        { name: "Fused Zamasu", anime: "Dragon Ball Super" },
        { name: "Golden Frieza (DBS)", anime: "Dragon Ball Super" },
        { name: "Gohan (DBS: Super Hero)", anime: "Dragon Ball Super" },

        // Naruto (Part 1)
        { name: "Naruto Uzumaki (Part 1)", anime: "Naruto (Part 1)" },
        { name: "Sasuke Uchiha (Part 1)", anime: "Naruto (Part 1)" },
        { name: "Rock Lee", anime: "Naruto (Part 1)" },
        { name: "Kakashi Hatake (Part 1)", anime: "Naruto (Part 1)" },
        { name: "Orochimaru", anime: "Naruto (Part 1)" },
        { name: "Neji Hyuga", anime: "Naruto (Part 1)" },
        { name: "Kabuto", anime: "Naruto (Part 1)" },
        { name: "Jiraiya", anime: "Naruto (Part 1)" },
        { name: "Tsunade", anime: "Naruto (Part 1)" },
        { name: "Hiruzen Sarutobi", anime: "Naruto (Part 1)" },

        // Naruto Shippuden
        { name: "Itachi Uchiha", anime: "Naruto Shippuden" },
        { name: "Pain (Nagato)", anime: "Naruto Shippuden" },
        { name: "Madara Uchiha", anime: "Naruto Shippuden" },
        { name: "Obito Uchiha (Tobi)", anime: "Naruto Shippuden" },
        { name: "Minato Namikaze", anime: "Naruto Shippuden" },
        { name: "Might Guy", anime: "Naruto Shippuden" },
        { name: "Killer Bee", anime: "Naruto Shippuden" },
        { name: "Hashirama Senju", anime: "Naruto Shippuden" },
        { name: "Kaguya Otsutsuki", anime: "Naruto Shippuden" },
        { name: "Shikamaru Nara (Shippuden)", anime: "Naruto Shippuden" },
        { name: "Naruto Uzumaki (Shippuden)", anime: "Naruto Shippuden" },
        { name: "Sasuke Uchiha (Shippuden)", anime: "Naruto Shippuden" },
        { name: "KAguya Otsutsuki", anime: "Naruto Shippuden" },

        // Attack on Titan
        { name: "Eren Yeager", anime: "Attack on Titan" },
        { name: "Mikasa Ackerman", anime: "Attack on Titan" },
        { name: "Levi Ackerman", anime: "Attack on Titan" },
        { name: "Erwin Smith", anime: "Attack on Titan" },
        { name: "Armin Arlert", anime: "Attack on Titan" },
        { name: "Hange Zoë", anime: "Attack on Titan" },
        { name: "Jean Kirstein", anime: "Attack on Titan" },
        { name: "Reiner Braun", anime: "Attack on Titan" },
        { name: "Historia Reiss", anime: "Attack on Titan" },
        { name: "Zeke Yeager", anime: "Attack on Titan" },

        // My Hero Academia
        { name: "Deku (Izuku Midoriya)", anime: "My Hero Academia" },
        { name: "Bakugo Katsuki", anime: "My Hero Academia" },
        { name: "Shoto Todoroki", anime: "My Hero Academia" },
        { name: "All Might", anime: "My Hero Academia" },
        { name: "Dabi", anime: "My Hero Academia" },
        { name: "Shigaraki Tomura", anime: "My Hero Academia" },
        { name: "Endeavor", anime: "My Hero Academia" },
        { name: "Hawks", anime: "My Hero Academia" },
        { name: "Ochaco Uraraka", anime: "My Hero Academia" },
        { name: "Shota Aizawa (Eraser Head)", anime: "My Hero Academia" },

        // Jujutsu Kaisen
        { name: "Yuji Itadori", anime: "Jujutsu Kaisen" },
        { name: "Megumi Fushiguro", anime: "Jujutsu Kaisen" },
        { name: "Nobara Kugisaki", anime: "Jujutsu Kaisen" },
        { name: "Gojo Satoru", anime: "Jujutsu Kaisen" },
        { name: "Sukuna", anime: "Jujutsu Kaisen" },
        { name: "Yuta Okkotsu", anime: "Jujutsu Kaisen" },
        { name: "Maki Zenin", anime: "Jujutsu Kaisen" },
        { name: "Toji Fushiguro", anime: "Jujutsu Kaisen" },
        { name: "Suguru Geto", anime: "Jujutsu Kaisen" },
        { name: "Kento Nanami", anime: "Jujutsu Kaisen" },

        // Black Clover
        { name: "Asta", anime: "Black Clover" },
        { name: "Yuno", anime: "Black Clover" },
        { name: "Noelle Silva", anime: "Black Clover" },
        { name: "Yami Sukehiro", anime: "Black Clover" },
        { name: "Julius Novachrono", anime: "Black Clover" },
        { name: "Luck Voltia", anime: "Black Clover" },
        { name: "Charmy Pappitson", anime: "Black Clover" },
        { name: "Mereoleona Vermillion", anime: "Black Clover" },
        { name: "Nozel Silva", anime: "Black Clover" },
        { name: "Fuegoleon Vermillion", anime: "Black Clover" },

        // Fire Force
        { name: "Shinra Kusakabe", anime: "Fire Force" },
        { name: "Arthur Boyle", anime: "Fire Force" },
        { name: "Benimaru Shinmon", anime: "Fire Force" },
        { name: "Tamaki Kotatsu", anime: "Fire Force" },
        { name: "Joker", anime: "Fire Force" },
        { name: "Maki Oze", anime: "Fire Force" },
        { name: "Iris", anime: "Fire Force" },
        { name: "Princess Hibana", anime: "Fire Force" },
        { name: "Sho Kusakabe", anime: "Fire Force" },
        { name: "Leonard Burns", anime: "Fire Force" },

        // Kaiju No. 8
        { name: "Kafka Hibino", anime: "Kaiju No. 8" },
        { name: "Mina Ashiro", anime: "Kaiju No. 8" },
        { name: "Reno Ichikawa", anime: "Kaiju No. 8" },
        { name: "Kikoru Shinomiya", anime: "Kaiju No. 8" },
        { name: "Soshiro Hoshina", anime: "Kaiju No. 8" },
        { name: "Gen Narumi", anime: "Kaiju No. 8" },
        { name: "Isao Shinomiya", anime: "Kaiju No. 8" },
        { name: "Haruichi Izumo", anime: "Kaiju No. 8" },
        { name: "Aoi Kaguragi", anime: "Kaiju No. 8" },
        { name: "Kaiju No. 9", anime: "Kaiju No. 8" },

        // Hunter x Hunter
        { name: "Gon Freecss", anime: "Hunter x Hunter" },
        { name: "Killua Zoldyck", anime: "Hunter x Hunter" },
        { name: "Kurapika", anime: "Hunter x Hunter" },
        { name: "Hisoka", anime: "Hunter x Hunter" },
        { name: "Chrollo Lucilfer", anime: "Hunter x Hunter" },
        { name: "Leorio Paradinight", anime: "Hunter x Hunter" },
        { name: "Isaac Netero", anime: "Hunter x Hunter" },
        { name: "Meruem", anime: "Hunter x Hunter" },
        { name: "Neferpitou", anime: "Hunter x Hunter" },
        { name: "Biscuit Krueger", anime: "Hunter x Hunter" },

        // FMAB
        { name: "Edward Elric", anime: "Fullmetal Alchemist: Brotherhood" },
        { name: "Alphonse Elric", anime: "Fullmetal Alchemist: Brotherhood" },
        { name: "Roy Mustang", anime: "Fullmetal Alchemist: Brotherhood" },
        { name: "Scar", anime: "Fullmetal Alchemist: Brotherhood" },
        { name: "King Bradley", anime: "Fullmetal Alchemist: Brotherhood" },
        { name: "Riza Hawkeye", anime: "Fullmetal Alchemist: Brotherhood" },
        { name: "Winry Rockbell", anime: "Fullmetal Alchemist: Brotherhood" },
        { name: "Ling Yao", anime: "Fullmetal Alchemist: Brotherhood" },
        { name: "Greed (Ling)", anime: "Fullmetal Alchemist: Brotherhood" },
        { name: "Envy", anime: "Fullmetal Alchemist: Brotherhood" },

        // Yu Yu Hakusho
        { name: "Yusuke Urameshi", anime: "Yu Yu Hakusho" },
        { name: "Kuwabara", anime: "Yu Yu Hakusho" },
        { name: "Kurama", anime: "Yu Yu Hakusho" },
        { name: "Hiei", anime: "Yu Yu Hakusho" },
        { name: "Toguro", anime: "Yu Yu Hakusho" },
        { name: "Genkai", anime: "Yu Yu Hakusho" },
        { name: "Shinobu Sensui", anime: "Yu Yu Hakusho" },
        { name: "Koenma", anime: "Yu Yu Hakusho" },
        { name: "Raizen", anime: "Yu Yu Hakusho" },
        { name: "Yomi", anime: "Yu Yu Hakusho" },

        // Rurouni Kenshin
        { name: "Kenshin Himura", anime: "Rurouni Kenshin" },
        { name: "Kaoru Kamiya", anime: "Rurouni Kenshin" },
        { name: "Sanosuke Sagara", anime: "Rurouni Kenshin" },
        { name: "Makoto Shishio", anime: "Rurouni Kenshin" },
        { name: "Aoshi Shinomori", anime: "Rurouni Kenshin" },
        { name: "Saito Hajime", anime: "Rurouni Kenshin" },
        { name: "Yahiko Myojin", anime: "Rurouni Kenshin" },
        { name: "Megumi Takani", anime: "Rurouni Kenshin" },
        { name: "Sojiro Seta", anime: "Rurouni Kenshin" },
        { name: "Enishi Yukishiro", anime: "Rurouni Kenshin" },

        // Fairy Tail
        { name: "Natsu Dragneel", anime: "Fairy Tail" },
        { name: "Lucy Heartfilia", anime: "Fairy Tail" },
        { name: "Erza Scarlet", anime: "Fairy Tail" },
        { name: "Gray Fullbuster", anime: "Fairy Tail" },
        { name: "Zeref", anime: "Fairy Tail" },
        { name: "Wendy Marvell", anime: "Fairy Tail" },
        { name: "Jellal Fernandes", anime: "Fairy Tail" },
        { name: "Gajeel Redfox", anime: "Fairy Tail" },
        { name: "Mirajane Strauss", anime: "Fairy Tail" },
        { name: "Laxus Dreyar", anime: "Fairy Tail" },

        // Akame ga Kill!
        { name: "Akame", anime: "Akame ga Kill!" },
        { name: "Tatsumi", anime: "Akame ga Kill!" },
        { name: "Esdeath", anime: "Akame ga Kill!" },
        { name: "Leone", anime: "Akame ga Kill!" },
        { name: "Mine", anime: "Akame ga Kill!" },
        { name: "Najenda", anime: "Akame ga Kill!" },
        { name: "Bulat", anime: "Akame ga Kill!" },
        { name: "Chelsea", anime: "Akame ga Kill!" },
        { name: "Wave", anime: "Akame ga Kill!" },
        { name: "Kurome", anime: "Akame ga Kill!" },

        // Tokyo Ghoul
        { name: "Ken Kaneki", anime: "Tokyo Ghoul" },
        { name: "Touka Kirishima", anime: "Tokyo Ghoul" },
        { name: "Juuzou Suzuya", anime: "Tokyo Ghoul" },
        { name: "Kuzen Yoshimura", anime: "Tokyo Ghoul" },
        { name: "Koutarou Amon", anime: "Tokyo Ghoul" },
        { name: "Rize Kamishiro", anime: "Tokyo Ghoul" },
        { name: "Shuu Tsukiyama", anime: "Tokyo Ghoul" },
        { name: "Eto Yoshimura", anime: "Tokyo Ghoul" },
        { name: "Kishou Arima", anime: "Tokyo Ghoul" },
        { name: "Hinami Fueguchi", anime: "Tokyo Ghoul" },

        // Tokyo Revengers
        { name: "Takemichi Hanagaki", anime: "Tokyo Revengers" },
        { name: "Mikey (Manjiro Sano)", anime: "Tokyo Revengers" },
        { name: "Draken", anime: "Tokyo Revengers" },
        { name: "Kisaki Tetta", anime: "Tokyo Revengers" },
        { name: "Baji Keisuke", anime: "Tokyo Revengers" },
        { name: "Chifuyu Matsuno", anime: "Tokyo Revengers" },
        { name: "Kazutora Hanemiya", anime: "Tokyo Revengers" },
        { name: "Hakkai Shiba", anime: "Tokyo Revengers" },
        { name: "Taiju Shiba", anime: "Tokyo Revengers" },
        { name: "Emma Sano", anime: "Tokyo Revengers" },

        // Blue Exorcist
        { name: "Rin Okumura", anime: "Blue Exorcist" },
        { name: "Yukio Okumura", anime: "Blue Exorcist" },
        { name: "Shura Kirigakure", anime: "Blue Exorcist" },
        { name: "Mephisto Pheles", anime: "Blue Exorcist" },
        { name: "Amaimon", anime: "Blue Exorcist" },
        { name: "Izumo Kamiki", anime: "Blue Exorcist" },
        { name: "Ryuji Suguro", anime: "Blue Exorcist" },
        { name: "Shiemi Moriyama", anime: "Blue Exorcist" },
        { name: "Shiro Fujimoto", anime: "Blue Exorcist" },
        { name: "Konekomaru Miwa", anime: "Blue Exorcist" },

        // Seraph of the End
        { name: "Yuuichirou Hyakuya", anime: "Seraph of the End" },
        { name: "Mikaela Hyakuya", anime: "Seraph of the End" },
        { name: "Guren Ichinose", anime: "Seraph of the End" },
        { name: "Shinoa Hiragi", anime: "Seraph of the End" },
        { name: "Ferid Bathory", anime: "Seraph of the End" },
        { name: "Krul Tepes", anime: "Seraph of the End" },
        { name: "Mitsuba Sangu", anime: "Seraph of the End" },
        { name: "Yoichi Saotome", anime: "Seraph of the End" },
        { name: "Kimizuki Shihou", anime: "Seraph of the End" },
        { name: "Mahiru Hiragi", anime: "Seraph of the End" },

        // Wind Breaker
        { name: "Haruka Sakura", anime: "Wind Breaker" },
        { name: "Hajime Umemiya", anime: "Wind Breaker" },
        { name: "Kyotaro Sugishita", anime: "Wind Breaker" },
        { name: "Hayato Suo", anime: "Wind Breaker" },
        { name: "Jo Togame", anime: "Wind Breaker" },
        { name: "Akihiko Nirei", anime: "Wind Breaker" },
        { name: "Ren Kaji", anime: "Wind Breaker" },
        { name: "Taiga Tsugeura", anime: "Wind Breaker" },
        { name: "Mitsuki Kiryu", anime: "Wind Breaker" },
        { name: "Masaki Anzai", anime: "Wind Breaker" },

        // Solo Leveling
        { name: "Sung Jinwoo", anime: "Solo Leveling" },
        { name: "Cha Hae-In", anime: "Solo Leveling" },
        { name: "Yoo Jinho", anime: "Solo Leveling" },
        { name: "Igris", anime: "Solo Leveling" },
        { name: "Beru", anime: "Solo Leveling" },
        { name: "Go Gunhee", anime: "Solo Leveling" },
        { name: "Thomas Andre", anime: "Solo Leveling" },
        { name: "Liu Zhigang", anime: "Solo Leveling" },
        { name: "Antares", anime: "Solo Leveling" },
        { name: "Kaisel", anime: "Solo Leveling" },

        // Shangri-La Frontier
        { name: "Sunraku (Rakuro Hizutome)", anime: "Shangri-La Frontier" },
        { name: "Psyger-0 (Rei Saiga)", anime: "Shangri-La Frontier" },
        { name: "Arthur Pencilgon", anime: "Shangri-La Frontier" },
        { name: "OiKatzo", anime: "Shangri-La Frontier" },
        { name: "Emul", anime: "Shangri-La Frontier" },
        { name: "Wezaemon the Tombguard", anime: "Shangri-La Frontier" },
        { name: "Lycaon the Nightslayer", anime: "Shangri-La Frontier" },
        { name: "Vysache", anime: "Shangri-La Frontier" },
        { name: "Ctarnidd of the Abyss", anime: "Shangri-La Frontier" },
        { name: "Setsuna", anime: "Shangri-La Frontier" },

        // Seven Deadly Sins
        { name: "Meliodas", anime: "Seven Deadly Sins" },
        { name: "Ban", anime: "Seven Deadly Sins" },
        { name: "Escanor", anime: "Seven Deadly Sins" },
        { name: "King", anime: "Seven Deadly Sins" },
        { name: "Diane", anime: "Seven Deadly Sins" },
        { name: "Elizabeth Liones", anime: "Seven Deadly Sins" },
        { name: "Merlin", anime: "Seven Deadly Sins" },
        { name: "Gowther", anime: "Seven Deadly Sins" },
        { name: "Hawk", anime: "Seven Deadly Sins" },
        { name: "Estarossa (Mael)", anime: "Seven Deadly Sins" },

        // Death Note
        { name: "Light Yagami", anime: "Death Note" },
        { name: "L", anime: "Death Note" },
        { name: "Misa Amane", anime: "Death Note" },
        { name: "Near", anime: "Death Note" },
        { name: "Ryuk", anime: "Death Note" },
        { name: "Soichiro Yagami", anime: "Death Note" },
        { name: "Touta Matsuda", anime: "Death Note" },
        { name: "Teru Mikami", anime: "Death Note" },
        { name: "Naomi Misora", anime: "Death Note" },
        { name: "Kiyomi Takada", anime: "Death Note" },

        // Classroom of the Elite
        { name: "Ayanokoji Kiyotaka", anime: "Classroom of the Elite" },
        { name: "Suzune Horikita", anime: "Classroom of the Elite" },
        { name: "Kikyo Kushida", anime: "Classroom of the Elite" },
        { name: "Kakeru Ryuen", anime: "Classroom of the Elite" },
        { name: "Arisu Sakayanagi", anime: "Classroom of the Elite" },
        { name: "Kei Karuizawa", anime: "Classroom of the Elite" },
        { name: "Honami Ichinose", anime: "Classroom of the Elite" },
        { name: "Manabu Horikita", anime: "Classroom of the Elite" },
        { name: "Rokusuke Koenji", anime: "Classroom of the Elite" },
        { name: "Sae Chabashira", anime: "Classroom of the Elite" },

        // Code Geass
        { name: "Lelouch vi Britannia", anime: "Code Geass" },
        { name: "Suzaku Kururugi", anime: "Code Geass" },
        { name: "C.C.", anime: "Code Geass" },
        { name: "Kallen Kozuki", anime: "Code Geass" },
        { name: "Schneizel el Britannia", anime: "Code Geass" },
        { name: "Nunnally vi Britannia", anime: "Code Geass" },
        { name: "Cornelia li Britannia", anime: "Code Geass" },
        { name: "Euphemia li Britannia", anime: "Code Geass" },
        { name: "Charles zi Britannia", anime: "Code Geass" },
        { name: "Jeremiah Gottwald", anime: "Code Geass" },

        // Death Parade
        { name: "Decim", anime: "Death Parade" },
        { name: "Chiyuki", anime: "Death Parade" },
        { name: "Nona", anime: "Death Parade" },
        { name: "Ginti", anime: "Death Parade" },
        { name: "Clavis", anime: "Death Parade" },
        { name: "Oculus", anime: "Death Parade" },
        { name: "Quin", anime: "Death Parade" },
        { name: "Mai Takada", anime: "Death Parade" },
        { name: "Misaki Tachibana", anime: "Death Parade" },
        { name: "Naoki Tachibana", anime: "Death Parade" },

        // Overlord
        { name: "Ainz Ooal Gown", anime: "Overlord" },
        { name: "Albedo", anime: "Overlord" },
        { name: "Demiurge", anime: "Overlord" },
        { name: "Shalltear Bloodfallen", anime: "Overlord" },
        { name: "Sebas Tian", anime: "Overlord" },
        { name: "Cocytus", anime: "Overlord" },
        { name: "Aura Bella Fiora", anime: "Overlord" },
        { name: "Mare Bello Fiore", anime: "Overlord" },
        { name: "Pandora's Actor", anime: "Overlord" },
        { name: "Victim", anime: "Overlord" },

        // Shield Hero
        { name: "Naofumi Iwatani", anime: "The Rising of the Shield Hero" },
        { name: "Raphtalia", anime: "The Rising of the Shield Hero" },
        { name: "Filo", anime: "The Rising of the Shield Hero" },
        { name: "Motoyasu", anime: "The Rising of the Shield Hero" },
        { name: "Malty", anime: "The Rising of the Shield Hero" },
        { name: "Fitoria", anime: "The Rising of the Shield Hero" },
        { name: "Queen Mirellia", anime: "The Rising of the Shield Hero" },
        { name: "Melty Q Melromarc", anime: "The Rising of the Shield Hero" },
        { name: "Glass", anime: "The Rising of the Shield Hero" },
        { name: "L'Arc Berg", anime: "The Rising of the Shield Hero" },

        // Re:Zero
        { name: "Subaru Natsuki", anime: "Re:Zero" },
        { name: "Emilia", anime: "Re:Zero" },
        { name: "Rem", anime: "Re:Zero" },
        { name: "Ram", anime: "Re:Zero" },
        { name: "Roswaal", anime: "Re:Zero" },
        { name: "Beatrice", anime: "Re:Zero" },
        { name: "Otto Suwen", anime: "Re:Zero" },
        { name: "Garfiel Tinsel", anime: "Re:Zero" },
        { name: "Elsa Granhiert", anime: "Re:Zero" },
        { name: "Echidna", anime: "Re:Zero" },

        // Mushoku Tensei
        { name: "Rudeus Greyrat", anime: "Mushoku Tensei" },
        { name: "Eris Boreas Greyrat", anime: "Mushoku Tensei" },
        { name: "Roxy Migurdia", anime: "Mushoku Tensei" },
        { name: "Sylphiette", anime: "Mushoku Tensei" },
        { name: "Orsted", anime: "Mushoku Tensei" },
        { name: "Paul Greyrat", anime: "Mushoku Tensei" },
        { name: "Zenith Greyrat", anime: "Mushoku Tensei" },
        { name: "Ruijerd Superdia", anime: "Mushoku Tensei" },
        { name: "Ghislaine Dedoldia", anime: "Mushoku Tensei" },
        { name: "Kishirika Kishirisu", anime: "Mushoku Tensei" },

        // Arifureta
        { name: "Hajime Nagumo", anime: "Arifureta" },
        { name: "Yue", anime: "Arifureta" },
        { name: "Shea Haulia", anime: "Arifureta" },
        { name: "Tio Klarus", anime: "Arifureta" },
        { name: "Kaori Shirasaki", anime: "Arifureta" },
        { name: "Myu", anime: "Arifureta" },
        { name: "Yuka Sonobe", anime: "Arifureta" },
        { name: "Kouki Amanogawa", anime: "Arifureta" },
        { name: "Endou Kousuke", anime: "Arifureta" },
        { name: "Meld Loggins", anime: "Arifureta" },

        // Tsukimichi
        { name: "Makoto Misumi", anime: "Tsukimichi: Moonlit Fantasy" },
        { name: "Tomoe", anime: "Tsukimichi: Moonlit Fantasy" },
        { name: "Mio", anime: "Tsukimichi: Moonlit Fantasy" },
        { name: "Sofia Bulga", anime: "Tsukimichi: Moonlit Fantasy" },
        { name: "Lime Latte", anime: "Tsukimichi: Moonlit Fantasy" },
        { name: "Shiki", anime: "Tsukimichi: Moonlit Fantasy" },
        { name: "Emma", anime: "Tsukimichi: Moonlit Fantasy" },
        { name: "Toa", anime: "Tsukimichi: Moonlit Fantasy" },
        { name: "Rona", anime: "Tsukimichi: Moonlit Fantasy" },
        { name: "Io", anime: "Tsukimichi: Moonlit Fantasy" },

        // Wrong Way to Use Healing Magic
        { name: "Usato", anime: "The Wrong Way to Use Healing Magic" },
        { name: "Rose", anime: "The Wrong Way to Use Healing Magic" },
        { name: "Suzune Inukami", anime: "The Wrong Way to Use Healing Magic" },
        { name: "Kazuki Ryuusen", anime: "The Wrong Way to Use Healing Magic" },
        { name: "Amako", anime: "The Wrong Way to Use Healing Magic" },
        { name: "Felm", anime: "The Wrong Way to Use Healing Magic" },
        { name: "Gurd", anime: "The Wrong Way to Use Healing Magic" },
        { name: "Blurin", anime: "The Wrong Way to Use Healing Magic" },
        { name: "Orga", anime: "The Wrong Way to Use Healing Magic" },
        { name: "Nero", anime: "The Wrong Way to Use Healing Magic" },

        // Beast Tamer
        { name: "Rein Shroud", anime: "Beast Tamer" },
        { name: "Kanade", anime: "Beast Tamer" },
        { name: "Tania", anime: "Beast Tamer" },
        { name: "Sora", anime: "Beast Tamer" },
        { name: "Runa", anime: "Beast Tamer" },
        { name: "Arios Orlando", anime: "Beast Tamer" },
        { name: "Nina", anime: "Beast Tamer" },
        { name: "Stella", anime: "Beast Tamer" },
        { name: "Helen", anime: "Beast Tamer" },
        { name: "Natalie", anime: "Beast Tamer" },

        // Overly Cautious Hero
        { name: "Seiya Ryuuguuin", anime: "Overly Cautious Hero" },
        { name: "Ristarte", anime: "Overly Cautious Hero" },
        { name: "Valkyrie", anime: "Overly Cautious Hero" },
        { name: "Adenela", anime: "Overly Cautious Hero" },
        { name: "Aria", anime: "Overly Cautious Hero" },
        { name: "Mash", anime: "Overly Cautious Hero" },
        { name: "Cerceus", anime: "Overly Cautious Hero" },
        { name: "Mitotis", anime: "Overly Cautious Hero" },
        { name: "Ishtar", anime: "Overly Cautious Hero" },
        { name: "Ariadoa", anime: "Overly Cautious Hero" },

        // Death March
        { name: "Satou Pendragon", anime: "Death March to the Parallel World Rhapsody" },
        { name: "Zena Marientail", anime: "Death March to the Parallel World Rhapsody" },
        { name: "Arisa", anime: "Death March to the Parallel World Rhapsody" },
        { name: "Lulu", anime: "Death March to the Parallel World Rhapsody" },
        { name: "Pochi", anime: "Death March to the Parallel World Rhapsody" },
        { name: "Tama", anime: "Death March to the Parallel World Rhapsody" },
        { name: "Nana", anime: "Death March to the Parallel World Rhapsody" },
        { name: "Mia", anime: "Death March to the Parallel World Rhapsody" },
        { name: "Zen", anime: "Death March to the Parallel World Rhapsody" },
        { name: "Dryad", anime: "Death March to the Parallel World Rhapsody" },

        // Smartphone Isekai
        { name: "Touya Mochizuki", anime: "In Another World With My Smartphone" },
        { name: "Yumina Urnea Belfast", anime: "In Another World With My Smartphone" },
        { name: "Elze Silhoueska", anime: "In Another World With My Smartphone" },
        { name: "Linze Silhoueska", anime: "In Another World With My Smartphone" },
        { name: "Leen", anime: "In Another World With My Smartphone" },
        { name: "Yae Kokonoe", anime: "In Another World With My Smartphone" },
        { name: "Sushie Ernea Ortlinde", anime: "In Another World With My Smartphone" },
        { name: "Leonia", anime: "In Another World With My Smartphone" },
        { name: "Kohaku", anime: "In Another World With My Smartphone" },
        { name: "Hildegard Minhas", anime: "In Another World With My Smartphone" },

        // World’s Finest Assassin
        { name: "Lugh Tuatha Dé", anime: "The World’s Finest Assassin Gets Reincarnated as an Aristocrat" },
        { name: "Dia Viekone", anime: "The World’s Finest Assassin Gets Reincarnated as an Aristocrat" },
        { name: "Tarte", anime: "The World’s Finest Assassin Gets Reincarnated as an Aristocrat" },
        { name: "Maha", anime: "The World’s Finest Assassin Gets Reincarnated as an Aristocrat" },
        { name: "Cian Tuatha Dé", anime: "The World’s Finest Assassin Gets Reincarnated as an Aristocrat" },
        { name: "Epona", anime: "The World’s Finest Assassin Gets Reincarnated as an Aristocrat" },
        { name: "Epsylon", anime: "The World’s Finest Assassin Gets Reincarnated as an Aristocrat" },
        { name: "Viekone (House) Head", anime: "The World’s Finest Assassin Gets Reincarnated as an Aristocrat" },
        { name: "Illig Balor", anime: "The World’s Finest Assassin Gets Reincarnated as an Aristocrat" },
        { name: "Demon Lord (Target)", anime: "The World’s Finest Assassin Gets Reincarnated as an Aristocrat" },

        // Misfit
        { name: "Anos Voldigoad", anime: "The Misfit of Demon King Academy" },
        { name: "Misha Necron", anime: "The Misfit of Demon King Academy" },
        { name: "Sasha Necron", anime: "The Misfit of Demon King Academy" },
        { name: "Lay Glanzudlii", anime: "The Misfit of Demon King Academy" },
        { name: "Eleonore Bianca", anime: "The Misfit of Demon King Academy" },
        { name: "Misa Ilioroagu", anime: "The Misfit of Demon King Academy" },
        { name: "Avos Dilhevia", anime: "The Misfit of Demon King Academy" },
        { name: "Shin Reglia", anime: "The Misfit of Demon King Academy" },
        { name: "Eugo La Raviaz", anime: "The Misfit of Demon King Academy" },
        { name: "Melheis Boran", anime: "The Misfit of Demon King Academy" },

        // Tower of God
        { name: "Bam (Twenty-Fifth Baam)", anime: "Tower of God" },
        { name: "Khun Aguero Agnis", anime: "Tower of God" },
        { name: "Rak Wraithraiser", anime: "Tower of God" },
        { name: "Endorsi Jahad", anime: "Tower of God" },
        { name: "Rachel", anime: "Tower of God" },
        { name: "Ha Yuri Jahad", anime: "Tower of God" },
        { name: "Hwa Ryun", anime: "Tower of God" },
        { name: "Quant Blitz", anime: "Tower of God" },
        { name: "Urek Mazino", anime: "Tower of God" },
        { name: "Kallavan", anime: "Tower of God" },

        // Yu-Gi-Oh! Original
        { name: "Yugi Muto", anime: "Yu-Gi-Oh! (Original)" },
        { name: "Seto Kaiba", anime: "Yu-Gi-Oh! (Original)" },
        { name: "Joey Wheeler", anime: "Yu-Gi-Oh! (Original)" },
        { name: "Mai Valentine", anime: "Yu-Gi-Oh! (Original)" },
        { name: "Maximillion Pegasus", anime: "Yu-Gi-Oh! (Original)" },
        { name: "Tea Gardner (Anzu)", anime: "Yu-Gi-Oh! (Original)" },
        { name: "Yami Yugi (Pharaoh Atem)", anime: "Yu-Gi-Oh! (Original)" },
        { name: "Yami Bakura", anime: "Yu-Gi-Oh! (Original)" },
        { name: "Marik Ishtar", anime: "Yu-Gi-Oh! (Original)" },
        { name: "Weevil Underwood", anime: "Yu-Gi-Oh! (Original)" },

        // Cowboy Bebop
        { name: "Spike Spiegel", anime: "Cowboy Bebop" },
        { name: "Jet Black", anime: "Cowboy Bebop" },
        { name: "Faye Valentine", anime: "Cowboy Bebop" },
        { name: "Edward", anime: "Cowboy Bebop" },
        { name: "Vicious", anime: "Cowboy Bebop" },
        { name: "Ein", anime: "Cowboy Bebop" },
        { name: "Julia", anime: "Cowboy Bebop" },
        { name: "Fad", anime: "Cowboy Bebop" },
        { name: "Punch", anime: "Cowboy Bebop" },
        { name: "Laughing Bull", anime: "Cowboy Bebop" },

        // Parasyte
        { name: "Shinichi Izumi", anime: "Parasyte: The Maxim" },
        { name: "Migi", anime: "Parasyte: The Maxim" },
        { name: "Kana Kimishima", anime: "Parasyte: The Maxim" },
        { name: "Gotou", anime: "Parasyte: The Maxim" },
        { name: "Reiko Tamura", anime: "Parasyte: The Maxim" },
        { name: "Murano Satomi", anime: "Parasyte: The Maxim" },
        { name: "Ryoko Tamiya", anime: "Parasyte: The Maxim" },
        { name: "Mr. Izumi", anime: "Parasyte: The Maxim" },
        { name: "Uragami", anime: "Parasyte: The Maxim" },
        { name: "Mitsuo", anime: "Parasyte: The Maxim" },

        // Mashle
        { name: "Mash Burnedead", anime: "Mashle" },
        { name: "Finn Ames", anime: "Mashle" },
        { name: "Lance Crown", anime: "Mashle" },
        { name: "Dot Barrett", anime: "Mashle" },
        { name: "Abel Walker", anime: "Mashle" },
        { name: "Rayne Ames", anime: "Mashle" },
        { name: "Cell War", anime: "Mashle" },
        { name: "Margarette Macaron", anime: "Mashle" },
        { name: "Innocent Zero", anime: "Mashle" },
        { name: "Wahlberg Baigan", anime: "Mashle" },

        // Magi
        { name: "Aladdin", anime: "Magi: The Labyrinth of Magic" },
        { name: "Alibaba Saluja", anime: "Magi: The Labyrinth of Magic" },
        { name: "Morgiana", anime: "Magi: The Labyrinth of Magic" },
        { name: "Hakuryuu Ren", anime: "Magi: The Labyrinth of Magic" },
        { name: "Judar", anime: "Magi: The Labyrinth of Magic" },
        { name: "Kouen Ren", anime: "Magi: The Labyrinth of Magic" },
        { name: "Cassim", anime: "Magi: The Labyrinth of Magic" },
        { name: "Titus Alexius", anime: "Magi: The Labyrinth of Magic" },
        { name: "Kougyoku Ren", anime: "Magi: The Labyrinth of Magic" },
        { name: "Sharrkan", anime: "Magi: The Labyrinth of Magic" },

        // Magi: Sinbad
        { name: "Sinbad", anime: "Magi: Adventure of Sinbad" },
        { name: "Jafar", anime: "Magi: Adventure of Sinbad" },
        { name: "Hinahoho", anime: "Magi: Adventure of Sinbad" },
        { name: "Drakon", anime: "Magi: Adventure of Sinbad" },
        { name: "Yunan", anime: "Magi: Adventure of Sinbad" },
        { name: "Serendine", anime: "Magi: Adventure of Sinbad" },
        { name: "Ja'far", anime: "Magi: Adventure of Sinbad" },
        { name: "Masrur", anime: "Magi: Adventure of Sinbad" },
        { name: "Badr", anime: "Magi: Adventure of Sinbad" },
        { name: "Sphintus", anime: "Magi: Adventure of Sinbad" },

        // Pokémon
        { name: "Ash Ketchum", anime: "Pokémon" },
        { name: "Brock", anime: "Pokémon" },
        { name: "Misty", anime: "Pokémon" },
        { name: "Team Rocket (Jessie & James)", anime: "Pokémon" },
        { name: "Nurse Joy", anime: "Pokémon" },
        { name: "Pikachu", anime: "Pokémon" },
        { name: "Professor Oak", anime: "Pokémon" },
        { name: "Gary Oak", anime: "Pokémon" },
        { name: "Cynthia", anime: "Pokémon" },
        { name: "Giovanni", anime: "Pokémon" },
      ]
};
